### PR TITLE
Improve __PHP_Incomplete_Class support

### LINKED ISSUE #22: Deserialize unknown items to __PHP_Incomplete_Class
We should have an option `strict` with a boolean value, if it's set to true, we'll validate existance of each class in scope, otherwise we'd just convert it to `__PHP_Incomplete_Class` just like base php

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #22

### CODE REVIEW

**Comment by lukepolo** [comment]
Just gave this a try "php-serialize": "^1.2.0",

Session data has object, cannot deserialize { [AssertionError: Class League\OAuth1\Client\Credentials\TemporaryCredentials not found in given scope]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'Class League\\OAuth1\\Client\\Credentials\\TemporaryCredentials not found in given scope',
  generatedMessage: false }


Not sure if you push this to 1.2 yet

**Comment by lukepolo** [comment]
Great package so far! thanks for working on it

**Comment by steelbrain** [comment]
Are you sure you set the new `strict` option to `false`? You'll see it in the README

**Comment by lukepolo** [comment]
oups , ty

**Comment by lukepolo** [comment]
Damn your amazing. THanks so much for doing this , I can finally use my node app properly!

**Comment by steelbrain** [comment]
:+1:

**Pull request merged**
