### PR TITLE
Big Numbers serialization fix.

### PR DESCRIPTION
**Pull request by ilnicki**
Slightly slower but allows to correctly serialize/deserialize big Number values like Number.MAX_VALUE.

### CODE REVIEW

**Comment by steelbrain** [comment]
Thank you so much for this @ilnicki!

Could you please also add a test so we don't break this in future changes? Thanks again

**Comment by ilnicki** [comment]
Can not found what is "apm" and how to run tests. Is it Jasmine or Jest or whatever?

**Comment by ilnicki** [comment]
Added tests. Fixed exponent case mismatch.

**Comment by steelbrain** [comment]
Thank you for the fix and tests @ilnicki!

**Pull request merged**
