### PR TITLE
support nested serializable Classes + Objects

### LINKED ISSUE #5: support nested serializable Classes + Objects
add support for nested serializable Classes + Objects

### PR DESCRIPTION
**Pull request by cantremember**
fixes #5

### CODE REVIEW

**Comment by steelbrain** [comment]
:ok_hand: LGTM, waiting on CI

**Comment by cantremember** [comment]
💚 CircleCI passed!

**Comment by steelbrain** [comment]
CI looks happy, Thanks for taking care of this!

**Comment by cantremember** [comment]
you are welcome.  again -- you saved me a helluva lot of time

**Comment by steelbrain** [comment]
I am glad I could you liked it :bow:

**Comment by steelbrain** [comment]
Released in v1.1.1

**Comment by cantremember** [comment]
i want to commend you on your receptivity and communication, @steelbrain 

it made contributing a very rewarding experience for me and my project!

**Pull request merged**
